packages:
  - packages/ember-input
  - packages/ember-input-validation
  - packages/ember-ui
  - doc-app

catalog:
  "@babel/plugin-proposal-class-properties": ^7.18.6
  "@babel/plugin-proposal-decorators": ^7.24.7
  "@babel/plugin-transform-class-static-block": ^7.24.7
  "@babel/plugin-transform-typescript": ^7.25.2
  "@babel/runtime": ^7.25.0
  "@ember/optional-features": ^2.1.0
  "@ember/render-modifiers": ~2.1.0
  "@ember/test-helpers": ^3.3.1
  "@ember/test-waiters": ^3.0.2
  "@embroider/addon-dev": ^7.0.0
  "@embroider/addon-shim": ^1.8.9
  "@embroider/compat": ^3.6.1
  "@embroider/core": ^3.4.16
  "@embroider/webpack": ^4.0.5
  "@eonasdan/tempus-dominus": ^6.9.10
  "@glimmer/component": ^1.1.2
  "@glimmer/tracking": ^1.1.2
  "@glint/core": ^1.4.0
  "@glint/environment-ember-loose": ^1.4.0
  "@glint/environment-ember-template-imports": ^1.4.0
  "@glint/template": ^1.5.0
  "@popperjs/core": ^2.11.8
  "@rollup/plugin-babel": ^6.0.4
  "@rollup/plugin-node-resolve": ^15.2.3
  "@tsconfig/ember": ^3.0.8
  "@types/ember": ^4.0.11
  "@types/ember__application": ^4.0.11
  "@types/ember__array": ^4.0.10
  "@types/ember__component": ^4.0.22
  "@types/ember__controller": ^4.0.12
  "@types/ember__debug": ^4.0.8
  "@types/ember__destroyable": ^4.0.5
  "@types/ember__engine": ^4.0.11
  "@types/ember__error": ^4.0.6
  "@types/ember__helper": ^4.0.8
  "@types/ember__modifier": ^4.0.9
  "@types/ember__object": ^4.0.12
  "@types/ember__owner": ^4.0.9
  "@types/ember__polyfills": ^4.0.6
  "@types/ember__routing": ^4.0.22
  "@types/ember__runloop": ^4.0.10
  "@types/ember__service": ^4.0.9
  "@types/ember__string": ^3.16.3
  "@types/ember__template": ^4.0.7
  "@types/ember__test": ^4.0.6
  "@types/ember__utils": ^4.0.7
  "@types/ember-data__adapter": ^4.0.6
  "@types/ember-data__model": ^4.0.5
  "@types/ember-data__serializer": ^4.0.6
  "@types/qunit": 2.19.9
  "@types/rsvp": ^4.0.9
  "@typescript-eslint/eslint-plugin": ^7.18.0
  "@typescript-eslint/parser": ^7.18.0
  babel-plugin-ember-template-compilation: ^2.2.5
  broccoli-asset-rev: ^3.0.0
  concurrently: ^8.2.2
  ember-basic-dropdown: ^8.3.0
  ember-cli: ~5.12.0
  ember-cli-addon-docs: ^7.0.1
  ember-cli-addon-docs-yuidoc: ^1.1.0
  ember-cli-app-version: ^7.0.0
  ember-cli-babel: ^8.2.0
  ember-cli-clean-css: ^3.0.0
  ember-cli-dependency-checker: ^3.3.2
  ember-cli-deploy: ^2.0.0
  ember-cli-deploy-build: ^3.0.0
  ember-cli-deploy-git: ^1.3.4
  ember-cli-deploy-git-ci: ^1.0.1
  ember-cli-htmlbars: ^6.3.0
  ember-cli-inject-live-reload: ^2.1.0
  ember-click-outside: ^6.1.1
  ember-data: ~5.3.8
  ember-fetch: ^8.1.2
  ember-immer-changeset: ~1.0.2
  ember-intl: ~6.5.5
  ember-lifeline: ^7.0.0
  ember-load-initializers: ^2.1.2
  ember-page-title: ^8.2.3
  ember-power-select: ^8.3.1
  ember-power-select-with-create: ^3.0.0
  ember-qunit: ^8.1.0
  ember-resolver: ^12.0.1
  ember-template-imports: ^4.1.1
  ember-welcome-page: ^7.0.2
  ember-yeti-table: ~2.0.0
  eslint-config-prettier: ^9.1.0
  eslint-plugin-n: ^16.6.2
  eslint-plugin-prettier: ^5.2.1
  eslint-plugin-qunit: ^8.1.2
  font-awesome: ^4.7.0
  git-conventional-commits: ^2.6.7
  imask: ~7.6.1
  lefthook: ^1.8.2
  lerna: ^8.1.8
  loader.js: ^4.7.0
  pnpm-sync-dependencies-meta-injected: ^0.0.14
  prettier: ^3.3.3
  prettier-plugin-ember-template-tag: ^2.0.2
  qunit: ^2.22.0
  qunit-dom: ^3.2.1
  rollup: ^4.20.0
  rollup-plugin-copy: ^3.4.0
  rollup-plugin-glimmer-template-tag: ^0.4.1
  rollup-plugin-ts: ^3.4.5
  rsvp: ^4.8.5
  stylelint: ^15.11.0
  stylelint-config-standard: ^34.0.0
  stylelint-prettier: ^4.1.0
  type-fest: ^4.24.0
  yup: ~1.4.0
