import Service from '@ember/service';
import TpkValidationTextareaComponent from '../components/tpk-validation-textarea.gts';
import TpkValidationInputComponent from '../components/tpk-validation-input.gts';
import TpkValidationSelect from '../components/tpk-validation-select.gts';
import TpkValidationCheckboxComponent from '../components/tpk-validation-checkbox.gts';
import TpkValidationRadioComponent from '../components/tpk-validation-radio.gts';
import TpkValidationFileComponent from '../components/tpk-validation-file.gts';
import TpkValidationDatepickerComponent from '../components/tpk-validation-datepicker.gts';
import TpkValidationInputPrefabComponent from '../components/prefabs/tpk-validation-input.gts';
import TpkValidationSelectPrefabComponent from '../components/prefabs/tpk-validation-select.gts';
import TpkValidationSelectCreatePrefabComponent from '../components/prefabs/tpk-validation-select-create.gts';
import TpkValidationSelectSearchPrefabComponent from '../components/prefabs/tpk-validation-select-search.gts';
import TpkValidationDatepickerRangePrefabComponent from '../components/prefabs/tpk-validation-datepicker-range.gts';
import TpkValidationDatepickerPrefabComponent from '../components/prefabs/tpk-validation-datepicker.gts';
import TpkValidationTimepickerPrefabComponent from '../components/prefabs/tpk-validation-timepicker.gts';
import TpkValidationPasswordPrefabComponent from '../components/prefabs/tpk-validation-password.gts';
import TpkValidationCurrencyPrefabComponent from '../components/prefabs/tpk-validation-currency.gts';
import TpkValidationIntegerComponent from '../components/prefabs/tpk-validation-integer.gts';
import TpkValidationIBANPrefabComponent from '../components/prefabs/tpk-validation-iban.gts';
import TpkValidationMobilePrefabComponent from '../components/prefabs/tpk-validation-mobile.gts';
import TpkValidationNumberPrefabComponent from '../components/prefabs/tpk-validation-number.gts';
import TpkValidationBicPrefabComponent from '../components/prefabs/tpk-validation-bic.gts';
import TpkValidationNationalNumberPrefabComponent from '../components/prefabs/tpk-validation-national-number.gts';
import TpkValidationVATPrefabComponent from '../components/prefabs/tpk-validation-vat.gts';
import TpkValidationRadioGroupComponent from '../components/tpk-validation-radio-group.gts';
export default class TpkFormService extends Service {
    TpkInput: typeof TpkValidationInputComponent;
    TpkInputPrefab: typeof TpkValidationInputPrefabComponent;
    TpkTextarea: typeof TpkValidationTextareaComponent;
    TpkTextareaPrefab: import("@ember/component/template-only").TOC<import("../components/prefabs/tpk-validation-textarea.gts").TpkValidationTextareaPrefabSignature>;
    TpkSelect: typeof TpkValidationSelect;
    TpkSelectPrefab: typeof TpkValidationSelectPrefabComponent;
    TpkSelectCreatePrefab: typeof TpkValidationSelectCreatePrefabComponent;
    TpkSelectSearchPrefab: typeof TpkValidationSelectSearchPrefabComponent;
    TpkCheckbox: typeof TpkValidationCheckboxComponent;
    TpkCheckboxPrefab: import("@ember/component/template-only").TOC<import("../components/prefabs/tpk-validation-checkbox.gts").TpkValidationCheckboxPrefabSignature>;
    TpkRadio: typeof TpkValidationRadioComponent;
    TpkFile: typeof TpkValidationFileComponent;
    TpkDatepicker: typeof TpkValidationDatepickerComponent;
    TpkDatepickerPrefab: typeof TpkValidationDatepickerPrefabComponent;
    TpkDatepickerRangePrefab: typeof TpkValidationDatepickerRangePrefabComponent;
    TpkTimepickerPrefab: typeof TpkValidationTimepickerPrefabComponent;
    TpkPasswordPrefab: typeof TpkValidationPasswordPrefabComponent;
    TpkEmailPrefab: import("@ember/component/template-only").TOC<import("../components/prefabs/tpk-validation-email.gts").TpkValidationEmailComponentSignature>;
    TpkIbanPrefab: typeof TpkValidationIBANPrefabComponent;
    TpkBicPrefab: typeof TpkValidationBicPrefabComponent;
    TpkVatPrefab: typeof TpkValidationVATPrefabComponent;
    TpkNationalNumberPrefab: typeof TpkValidationNationalNumberPrefabComponent;
    TpkCurrencyPrefab: typeof TpkValidationCurrencyPrefabComponent;
    TpkIntegerPrefab: typeof TpkValidationIntegerComponent;
    TpkNumberPrefab: typeof TpkValidationNumberPrefabComponent;
    TpkMobilePrefab: typeof TpkValidationMobilePrefabComponent;
    TpkRadioGroup: typeof TpkValidationRadioGroupComponent;
    TpkRadioPrefab: import("@ember/component/template-only").TOC<import("../components/prefabs/tpk-validation-radio.gts").TpkValidationRadioPrefabComponentSignature>;
    TpkRadioGroupPrefab: import("@ember/component/template-only").TOC<import("../components/prefabs/tpk-validation-radio-group.gts").TpkValidationRadioGroupPrefabComponentSignature>;
    TpkFilePrefab: import("@ember/component/template-only").TOC<import("../components/prefabs/tpk-validation-file.gts").TpkValidationFilePrefabSignature>;
}
//# sourceMappingURL=tpk-form.d.ts.map