import Service from '@ember/service';
import TpkValidationTextareaComponent from '../components/tpk-validation-textarea';
import TpkValidationInputComponent from '../components/tpk-validation-input';
import TpkValidationSelect from '../components/tpk-validation-select';
import TpkValidationCheckboxComponent from '../components/tpk-validation-checkbox';
import TpkValidationRadioComponent from '../components/tpk-validation-radio';
import TpkValidationFileComponent from '../components/tpk-validation-file';
import TpkValidationDatepickerComponent from '../components/tpk-validation-datepicker';
import TpkValidationInputPrefabComponent from '../components/prefabs/tpk-validation-input';
import TpkValidationSelectPrefabComponent from '../components/prefabs/tpk-validation-select';
import TpkValidationSelectCreatePrefabComponent from '../components/prefabs/tpk-validation-select-create';
import TpkValidationSelectSearchPrefabComponent from '../components/prefabs/tpk-validation-select-search';
import TpkValidationDatepickerRangePrefabComponent from '../components/prefabs/tpk-validation-datepicker-range';
import TpkValidationDatepickerPrefabComponent from '../components/prefabs/tpk-validation-datepicker';
import TpkValidationTimepickerPrefabComponent from '../components/prefabs/tpk-validation-timepicker';
import TpkValidationPasswordPrefabComponent from '../components/prefabs/tpk-validation-password';
import TpkValidationCurrencyPrefabComponent from '../components/prefabs/tpk-validation-currency';
import TpkValidationIntegerComponent from '../components/prefabs/tpk-validation-integer';
import TpkValidationIBANPrefabComponent from '../components/prefabs/tpk-validation-iban';
import TpkValidationMobilePrefabComponent from '../components/prefabs/tpk-validation-mobile';
import TpkValidationNumberPrefabComponent from '../components/prefabs/tpk-validation-number';
import TpkValidationBicPrefabComponent from '../components/prefabs/tpk-validation-bic';
import TpkValidationNationalNumberPrefabComponent from '../components/prefabs/tpk-validation-national-number';
import TpkValidationVATPrefabComponent from '../components/prefabs/tpk-validation-vat';
import TpkValidationRadioGroupComponent from '../components/tpk-validation-radio-group';
export default class TpkFormService extends Service {
    TpkInput: typeof TpkValidationInputComponent;
    TpkInputPrefab: typeof TpkValidationInputPrefabComponent;
    TpkTextarea: typeof TpkValidationTextareaComponent;
    TpkTextareaPrefab: import("@ember/component/template-only").TOC<import('../components/prefabs/tpk-validation-textarea').TpkValidationTextareaPrefabSignature>;
    TpkSelect: typeof TpkValidationSelect;
    TpkSelectPrefab: typeof TpkValidationSelectPrefabComponent;
    TpkSelectCreatePrefab: typeof TpkValidationSelectCreatePrefabComponent;
    TpkSelectSearchPrefab: typeof TpkValidationSelectSearchPrefabComponent;
    TpkCheckbox: typeof TpkValidationCheckboxComponent;
    TpkCheckboxPrefab: import("@ember/component/template-only").TOC<import('../components/prefabs/tpk-validation-checkbox').TpkValidationCheckboxPrefabSignature>;
    TpkRadio: typeof TpkValidationRadioComponent;
    TpkFile: typeof TpkValidationFileComponent;
    TpkDatepicker: typeof TpkValidationDatepickerComponent;
    TpkDatepickerPrefab: typeof TpkValidationDatepickerPrefabComponent;
    TpkDatepickerRangePrefab: typeof TpkValidationDatepickerRangePrefabComponent;
    TpkTimepickerPrefab: typeof TpkValidationTimepickerPrefabComponent;
    TpkPasswordPrefab: typeof TpkValidationPasswordPrefabComponent;
    TpkEmailPrefab: import("@ember/component/template-only").TOC<import('../components/prefabs/tpk-validation-email').TpkValidationEmailComponentSignature>;
    TpkIbanPrefab: typeof TpkValidationIBANPrefabComponent;
    TpkBicPrefab: typeof TpkValidationBicPrefabComponent;
    TpkVatPrefab: typeof TpkValidationVATPrefabComponent;
    TpkNationalNumberPrefab: typeof TpkValidationNationalNumberPrefabComponent;
    TpkCurrencyPrefab: typeof TpkValidationCurrencyPrefabComponent;
    TpkIntegerPrefab: typeof TpkValidationIntegerComponent;
    TpkNumberPrefab: typeof TpkValidationNumberPrefabComponent;
    TpkMobilePrefab: typeof TpkValidationMobilePrefabComponent;
    TpkRadioGroup: typeof TpkValidationRadioGroupComponent;
    TpkRadioPrefab: import("@ember/component/template-only").TOC<import('../components/prefabs/tpk-validation-radio').TpkValidationRadioPrefabComponentSignature>;
    TpkRadioGroupPrefab: import("@ember/component/template-only").TOC<import('../components/prefabs/tpk-validation-radio-group').TpkValidationRadioGroupPrefabComponentSignature>;
    TpkFilePrefab: import("@ember/component/template-only").TOC<import('../components/prefabs/tpk-validation-file').TpkValidationFilePrefabSignature>;
}
//# sourceMappingURL=tpk-form.d.ts.map