import type TpkConfirmModalCancelComponent from './components/tpk-confirm-modal/cancel.gts';
import type TpkConfirmModalConfirmComponent from './components/tpk-confirm-modal/confirm.gts';
import type TpkModalContentComponent from './components/tpk-modal/content.gts';
import type LoadingIndicator from './components/tpk-loading-indicator.gts';
import type TpkActionsMenuComponent from './components/tpk-actions-menu.gts';
import type TpkModalComponent from './components/tpk-modal.gts';
import type TableGenericPaginationComponent from './components/tpk-table-generic/pagination.gts';
import type TableGenericBodyActionComponent from './components/tpk-table-generic/body/action.gts';
import type TableGenericBodyActionMenuComponent from './components/tpk-table-generic/body/action-menu.gts';
import type TableGenericBodyCellComponent from './components/tpk-table-generic/body/cell.gts';
import type TableGenericBodyComponent from './components/tpk-table-generic/body.gts';
import type TableGenericSearchBarComponent from './components/tpk-table-generic/search-bar.gts';
import type TableGenericHeaderComponent from './components/tpk-table-generic/header.gts';
import type TableGenericFooterComponent from './components/tpk-table-generic/footer.gts';
import type TableGenericHeaderCellComponent from './components/tpk-table-generic/header/cell.gts';
import type TableGenericTableComponent from './components/tpk-table-generic/table.gts';
import type TpkStepperStepComponent from './components/tpk-stepper/step.gts';
import type TpkStepperStepperComponent from './components/tpk-stepper/stepper.gts';
import type TpkConfirmModalComponent from './components/tpk-confirm-modal.gts';
import type TpkStepperStepHeaderComponent from './components/tpk-stepper/step/header.gts';
import type TableGenericComponent from './components/tpk-table-generic.gts';
import type TpkStepperComponent from './components/tpk-stepper.gts';
import type TpkStackListHeadComponent from './components/tpk-stack-list/head.gts';
import type StackListItemComponent from './components/tpk-stack-list/item.gts';
import type TpkStackListContentComponent from './components/tpk-stack-list/content.gts';
import type TpkActionsMenuElementComponent from './components/tpk-actions-menu/element.gts';
import type TpkStackListTitleComponent from './components/tpk-stack-list/title.gts';
import type TpkLazyImageComponent from './components/tpk-lazy-image.gts';

export default interface Registry {
  'tpk-actions-menu/element': typeof TpkActionsMenuElementComponent;
  'tpk-stack-list/title': typeof TpkStackListTitleComponent;
  'tpk-stack-list/content': typeof TpkStackListContentComponent;
  'tpk-stack-list/item': typeof StackListItemComponent;
  'tpk-lazy-image': typeof TpkLazyImageComponent;
  TpkLazyImage: typeof TpkLazyImageComponent;
  'TpkStackList::Item': typeof StackListItemComponent;
  'tpk-stack-list/head': typeof TpkStackListHeadComponent;
  'TpkStackList::Head': typeof TpkStackListHeadComponent;
  'tpk-stepper': typeof TpkStepperComponent;
  'tpk-table-generic': typeof TableGenericComponent;
  TpkTableGeneric: typeof TableGenericComponent;
  'tpk-confirm-modal/cancel': typeof TpkConfirmModalCancelComponent;
  'tpk-confirm-modal/confirm': typeof TpkConfirmModalConfirmComponent;
  'tpk-modal/content': typeof TpkModalContentComponent;
  'loading-indicator': typeof LoadingIndicator;
  LoadingIndicator: typeof LoadingIndicator;
  'tpk-actions-menu': typeof TpkActionsMenuComponent;
  TpkActionsMenu: typeof TpkActionsMenuComponent;
  'tpk-modal': typeof TpkModalComponent;
  TpkModal: typeof TpkModalComponent;
  'table-generic/pagination': typeof TableGenericPaginationComponent;
  'TableGeneric::Pagination': typeof TableGenericPaginationComponent;
  'table-generic/body/action': typeof TableGenericBodyActionComponent;
  'table-generic/body/action-menu': typeof TableGenericBodyActionMenuComponent;
  'table-generic/body/cell': typeof TableGenericBodyCellComponent;
  'table-generic/body': typeof TableGenericBodyComponent;
  'table-generic/search-bar': typeof TableGenericSearchBarComponent;
  'TableGeneric::SearchBar': typeof TableGenericSearchBarComponent;
  'table-generic/footer': typeof TableGenericFooterComponent;
  'table-generic/header': typeof TableGenericHeaderComponent;
  'table-generic/table': typeof TableGenericTableComponent;
  'table-generic/header/cell': typeof TableGenericHeaderCellComponent;
  'tpk-stepper/step/header': typeof TpkStepperStepHeaderComponent;
  'tpk-stepper/step': typeof TpkStepperStepComponent;
  'tpk-stepper/stepper': typeof TpkStepperStepperComponent;
  'tpk-confirm-modal': typeof TpkConfirmModalComponent;
}
