import TpkConfirmModalCancelComponent from './components/tpk-confirm-modal/cancel.gts';
import TpkConfirmModalConfirmComponent from './components/tpk-confirm-modal/confirm.gts';
import TpkModalContentComponent from './components/tpk-modal/content.gts';
import LoadingIndicator from './components/tpk-loading-indicator.gts';
import TpkActionsMenuComponent from './components/tpk-actions-menu.gts';
import TpkModalComponent from './components/tpk-modal.gts';
import TableGenericPaginationComponent from './components/tpk-table-generic/pagination.gts';
import TableGenericBodyActionComponent from './components/tpk-table-generic/body/action.gts';
import TableGenericBodyActionMenuComponent from './components/tpk-table-generic/body/action-menu.gts';
import TableGenericBodyCellComponent from './components/tpk-table-generic/body/cell.gts';
import TableGenericBodyComponent from './components/tpk-table-generic/body.gts';
import TableGenericSearchBarComponent from './components/tpk-table-generic/search-bar.gts';
import TableGenericHeaderComponent from './components/tpk-table-generic/header.gts';
import TableGenericFooterComponent from './components/tpk-table-generic/footer.gts';
import TableGenericHeaderCellComponent from './components/tpk-table-generic/header/cell.gts';
import TableGenericTableComponent from './components/tpk-table-generic/table.gts';
import TpkStepperStepComponent from './components/tpk-stepper/step.gts';
import TpkStepperStepperComponent from './components/tpk-stepper/stepper.gts';
import TpkConfirmModalComponent from './components/tpk-confirm-modal.gts';
import TpkStepperStepHeaderComponent from './components/tpk-stepper/step/header.gts';
import TableGenericComponent from './components/tpk-table-generic.gts';
import TpkStepperComponent from './components/tpk-stepper.gts';
import TpkStackListHeadComponent from './components/tpk-stack-list/head.gts';
import StackListItemComponent from './components/tpk-stack-list/item.gts';
import TpkStackListContentComponent from './components/tpk-stack-list/content.gts';
import TpkActionsMenuElementComponent from './components/tpk-actions-menu/element.gts';
import TpkStackListTitleComponent from './components/tpk-stack-list/title.gts';

export interface Registry {
  'tpk-actions-menu/element': typeof TpkActionsMenuElementComponent;
  'tpk-stack-list/title': typeof TpkStackListTitleComponent;
  'tpk-stack-list/content': typeof TpkStackListContentComponent;
  'tpk-stack-list/item': typeof StackListItemComponent;
  'TpkStackList::Item': typeof StackListItemComponent;
  'tpk-stack-list/head': typeof TpkStackListHeadComponent;
  'TpkStackList::Head': typeof TpkStackListHeadComponent;
  'tpk-stepper': typeof TpkStepperComponent;
  'table-generic': typeof TableGenericComponent;
  TpkTableGeneric: typeof TableGenericComponent;
  'tpk-confirm-modal/cancel': typeof TpkConfirmModalCancelComponent;
  'tpk-confirm-modal/confirm': typeof TpkConfirmModalConfirmComponent;
  'tpk-modal/content': typeof TpkModalContentComponent;
  'loading-indicator': typeof LoadingIndicator;
  LoadingIndicator: typeof LoadingIndicator;
  'tpk-actions-menu': typeof TpkActionsMenuComponent;
  TpkActionsMenu: typeof TpkActionsMenuComponent;
  'tpk-modal': typeof TpkModalComponent;
  TpkModal: typeof TpkModalComponent;
  'table-generic/pagination': typeof TableGenericPaginationComponent;
  'TableGeneric::Pagination': typeof TableGenericPaginationComponent;
  'table-generic/body/action': typeof TableGenericBodyActionComponent;
  'table-generic/body/action-menu': typeof TableGenericBodyActionMenuComponent;
  'table-generic/body/cell': typeof TableGenericBodyCellComponent;
  'table-generic/body': typeof TableGenericBodyComponent;
  'table-generic/search-bar': typeof TableGenericSearchBarComponent;
  'TableGeneric::SearchBar': typeof TableGenericSearchBarComponent;
  'table-generic/footer': typeof TableGenericFooterComponent;
  'table-generic/header': typeof TableGenericHeaderComponent;
  'table-generic/table': typeof TableGenericTableComponent;
  'table-generic/header/cell': typeof TableGenericHeaderCellComponent;
  'tpk-stepper/step/header': typeof TpkStepperStepHeaderComponent;
  'tpk-stepper/step': typeof TpkStepperStepComponent;
  'tpk-stepper/stepper': typeof TpkStepperStepperComponent;
  'tpk-confirm-modal': typeof TpkConfirmModalComponent;
}
