import type TpkConfirmModalCancelComponent from './components/tpk-confirm-modal/cancel';
import type TpkConfirmModalConfirmComponent from './components/tpk-confirm-modal/confirm';
import type TpkModalContentComponent from './components/tpk-modal/content';
import type LoadingIndicator from './components/tpk-loading-indicator';
import type TpkActionsMenuComponent from './components/tpk-actions-menu';
import type TpkModalComponent from './components/tpk-modal';
import type TableGenericPaginationComponent from './components/tpk-table-generic/pagination';
import type TableGenericBodyActionComponent from './components/tpk-table-generic/body/action';
import type TableGenericBodyActionMenuComponent from './components/tpk-table-generic/body/action-menu';
import type TableGenericBodyCellComponent from './components/tpk-table-generic/body/cell';
import type TableGenericBodyComponent from './components/tpk-table-generic/body';
import type TableGenericSearchBarComponent from './components/tpk-table-generic/search-bar';
import type TableGenericHeaderComponent from './components/tpk-table-generic/header';
import type TableGenericFooterComponent from './components/tpk-table-generic/footer';
import type TableGenericHeaderCellComponent from './components/tpk-table-generic/header/cell';
import type TableGenericTableComponent from './components/tpk-table-generic/table';
import type TpkConfirmModalComponent from './components/tpk-confirm-modal';
import type TableGenericComponent from './components/tpk-table-generic';
import type TpkStackListHeadComponent from './components/tpk-stack-list/head';
import type StackListItemComponent from './components/tpk-stack-list/item';
import type TpkStackListContentComponent from './components/tpk-stack-list/content';
import type TpkActionsMenuElementComponent from './components/tpk-actions-menu/element';
import type TpkStackListTitleComponent from './components/tpk-stack-list/title';
import type TpkConfirmModalPrefabComponent from './components/prefabs/tpk-confirm-modal-prefab';
import type TableGenericPrefabComponent from './components/prefabs/tpk-table-generic-prefab';
import type TpkDashboard from './components/prefabs/tpk-dashboard';
import type TpkThemeSelector from './components/prefabs/tpk-theme-selector';
export default interface Registry {
    'tpk-actions-menu/element': typeof TpkActionsMenuElementComponent;
    'tpk-stack-list/title': typeof TpkStackListTitleComponent;
    'tpk-stack-list/content': typeof TpkStackListContentComponent;
    'tpk-stack-list/item': typeof StackListItemComponent;
    'TpkStackList::Item': typeof StackListItemComponent;
    'tpk-stack-list/head': typeof TpkStackListHeadComponent;
    'TpkStackList::Head': typeof TpkStackListHeadComponent;
    'tpk-table-generic': typeof TableGenericComponent;
    TpkTableGeneric: typeof TableGenericComponent;
    'tpk-confirm-modal/cancel': typeof TpkConfirmModalCancelComponent;
    'tpk-confirm-modal/confirm': typeof TpkConfirmModalConfirmComponent;
    'tpk-modal/content': typeof TpkModalContentComponent;
    'loading-indicator': typeof LoadingIndicator;
    LoadingIndicator: typeof LoadingIndicator;
    'tpk-actions-menu': typeof TpkActionsMenuComponent;
    TpkActionsMenu: typeof TpkActionsMenuComponent;
    'tpk-modal': typeof TpkModalComponent;
    TpkModal: typeof TpkModalComponent;
    'table-generic/pagination': typeof TableGenericPaginationComponent;
    'TableGeneric::Pagination': typeof TableGenericPaginationComponent;
    'table-generic/body/action': typeof TableGenericBodyActionComponent;
    'table-generic/body/action-menu': typeof TableGenericBodyActionMenuComponent;
    'table-generic/body/cell': typeof TableGenericBodyCellComponent;
    'table-generic/body': typeof TableGenericBodyComponent;
    'table-generic/search-bar': typeof TableGenericSearchBarComponent;
    'TableGeneric::SearchBar': typeof TableGenericSearchBarComponent;
    'table-generic/footer': typeof TableGenericFooterComponent;
    'table-generic/header': typeof TableGenericHeaderComponent;
    'table-generic/table': typeof TableGenericTableComponent;
    'table-generic/header/cell': typeof TableGenericHeaderCellComponent;
    'tpk-confirm-modal': typeof TpkConfirmModalComponent;
    'tpk-confirm-modal-prefab': typeof TpkConfirmModalPrefabComponent;
    'tpk-table-generic-prefab': typeof TableGenericPrefabComponent;
    'tpk-dashboard-prefab': typeof TpkDashboard;
    'tpk-theme-selector': typeof TpkThemeSelector;
}
//# sourceMappingURL=template-registry.d.ts.map