import type TpkButtonComponent from './components/tpk-button';
import type TpkCheckboxComponent from './components/tpk-checkbox';
import type TpkCheckboxInputComponent from './components/tpk-checkbox-input';
import type TpkDatepicker from './components/tpk-datepicker';
import type TpkDatepickerInputComponent from './components/tpk-datepicker-input';
import type TpkFileComponent from './components/tpk-file';
import type TpkFileInputComponent from './components/tpk-file/input';
import type TpkInputComponent from './components/tpk-input';
import type TpkInputInputComponent from './components/tpk-input/input';
import type TpkLabel from './components/tpk-label';
import type TpkRadioComponent from './components/tpk-radio';
import type TpkRadioInputComponent from './components/tpk-radio/input';
import type TpkSelectComponent from './components/tpk-select';
import type TpkSelectOptionComponent from './components/tpk-select/option';
import type TpkTextareaComponent from './components/tpk-textarea';
import type TpkTextareaInputComponent from './components/tpk-textarea/input';
import type tpkFocusTrap from './modifiers/focus-trap';
import type TpkTogglePrefabComponent from './components/prefabs/tpk-toggle';
import type TpkButtonPrefabComponent from './components/prefabs/tpk-prefab-button';
export default interface Registry {
    'tpk-label': typeof TpkLabel;
    TpkLabel: typeof TpkLabel;
    'tpk-checkbox/input': typeof TpkCheckboxInputComponent;
    TpkCheckboxInput: typeof TpkCheckboxInputComponent;
    'tpk-datepicker/input': typeof TpkDatepickerInputComponent;
    TpkDatepickerInput: typeof TpkDatepickerInputComponent;
    'tpk-file/input': typeof TpkFileInputComponent;
    TpkFileInput: typeof TpkFileInputComponent;
    'tpk-input/input': typeof TpkInputInputComponent;
    TpkInputInput: typeof TpkInputInputComponent;
    'tpk-radio/input': typeof TpkRadioInputComponent;
    TpkRadioInput: typeof TpkRadioInputComponent;
    'tpk-textarea/input': typeof TpkTextareaInputComponent;
    TpkTextareaInput: typeof TpkTextareaInputComponent;
    'tpk-button': typeof TpkButtonComponent;
    TpkButton: typeof TpkButtonComponent;
    'tpk-checkbox': typeof TpkCheckboxComponent;
    TpkCheckbox: typeof TpkCheckboxComponent;
    'tpk-datepicker': typeof TpkDatepicker;
    TpkDatepicker: typeof TpkDatepicker;
    'tpk-file': typeof TpkFileComponent;
    TpkFile: typeof TpkFileComponent;
    'tpk-input': typeof TpkInputComponent;
    TpkInput: typeof TpkInputComponent;
    'tpk-radio': typeof TpkRadioComponent;
    TpkRadio: typeof TpkRadioComponent;
    'tpk-select': typeof TpkSelectComponent;
    TpkSelect: typeof TpkSelectComponent;
    'tpk-select/option': typeof TpkSelectOptionComponent;
    TpkSelectOption: typeof TpkSelectOptionComponent;
    'tpk-textarea': typeof TpkTextareaComponent;
    TpkTextarea: typeof TpkTextareaComponent;
    'focus-trap': typeof tpkFocusTrap;
    TpkToggle: typeof TpkTogglePrefabComponent;
    'tpk-toggle': typeof TpkTogglePrefabComponent;
    TpkPrefabButton: typeof TpkButtonPrefabComponent;
    'tpk-prefab-button': typeof TpkButtonPrefabComponent;
}
//# sourceMappingURL=template-registry.d.ts.map