import Service from '@ember/service';
import { tracked } from '@glimmer/tracking';
import TpkValidationTextarea from '../components/tpk-validation-textarea.gts';
import TpkValidationInput from '../components/tpk-validation-input.gts';
import TpkValidationSelect from '../components/tpk-validation-select.gts';
import TpkValidationCheckbox from '../components/tpk-validation-checkbox.gts';
import TpkValidationRadio from '../components/tpk-validation-radio.gts';
import TpkValidationFile from '../components/tpk-validation-file.gts';
import TpkValidationDatepicker from '../components/tpk-validation-datepicker.gts';
import TpkValidationInputPrefabComponent from '../components/prefabs/tpk-validation-input.gts';
import TpkValidationTextareaPrefabComponent from '../components/prefabs/tpk-validation-textarea.gts';
import TpkValidationSelectPrefabComponent from '../components/prefabs/tpk-validation-select.gts';
import TpkValidationSelectCreatePrefabComponent from '../components/prefabs/tpk-validation-select-create.gts';
import TpkValidationSelectSearchPrefabComponent from '../components/prefabs/tpk-validation-select-search.gts';
import TpkValidationCheckboxPrefabComponent from '../components/prefabs/tpk-validation-checkbox.gts';
import TpkValidationDatepickerRangePrefabComponent from '../components/prefabs/tpk-validation-datepicker-range.gts';
import TpkValidationDatepickerPrefabComponent from '../components/prefabs/tpk-validation-datepicker.gts';
import TpkValidationTimepickerPrefabComponent from '../components/prefabs/tpk-validation-timepicker.gts';
import TpkValidationPasswordPrefabComponent from '../components/prefabs/tpk-validation-password.gts';
import TpkValidationCurrencyPrefabComponent from '../components/prefabs/tpk-validation-currency.gts';
import TpkValidationIntegerComponent from '../components/prefabs/tpk-validation-integer.gts';
import TpkValidationEmailPrefabComponent from '../components/prefabs/tpk-validation-email.gts';
import TpkValidationIBANPrefabComponent from '../components/prefabs/tpk-validation-iban.gts';
import TpkValidationMobilePrefabComponent from '../components/prefabs/tpk-validation-mobile.gts';
import TpkValidationNumberPrefabComponent from '../components/prefabs/tpk-validation-number.gts';
import TpkValidationBicPrefabComponent from '../components/prefabs/tpk-validation-bic.gts';
import TpkValidationNationalNumberPrefabComponent from '../components/prefabs/tpk-validation-national-number.gts';
import TpkValidationVATPrefabComponent from '../components/prefabs/tpk-validation-vat.gts';
import TpkValidationRadioGroup from '../components/tpk-validation-radio-group.gts';
import TpkValidationRadioPrefabComponent from '../components/prefabs/tpk-validation-radio.gts';
import TpkValidationRadioGroupPrefabComponent from '../components/prefabs/tpk-validation-radio-group.gts';
import TpkValidationFilePrefabComponent from '../components/prefabs/tpk-validation-file.gts';

export default class TpkFormService extends Service {
  @tracked TpkInput = TpkValidationInput;
  @tracked TpkInputPrefab = TpkValidationInputPrefabComponent;
  @tracked TpkTextarea = TpkValidationTextarea;
  @tracked TpkTextareaPrefab = TpkValidationTextareaPrefabComponent;
  @tracked TpkSelect = TpkValidationSelect;
  @tracked TpkSelectPrefab = TpkValidationSelectPrefabComponent;
  @tracked TpkSelectCreatePrefab = TpkValidationSelectCreatePrefabComponent;
  @tracked TpkSelectSearchPrefab = TpkValidationSelectSearchPrefabComponent;
  @tracked TpkCheckbox = TpkValidationCheckbox;
  @tracked TpkCheckboxPrefab = TpkValidationCheckboxPrefabComponent;
  @tracked TpkRadio = TpkValidationRadio;
  @tracked TpkFile = TpkValidationFile;
  @tracked TpkDatepicker = TpkValidationDatepicker;
  @tracked TpkDatepickerPrefab = TpkValidationDatepickerPrefabComponent;
  @tracked TpkDatepickerRangePrefab =
    TpkValidationDatepickerRangePrefabComponent;
  @tracked TpkTimepickerPrefab = TpkValidationTimepickerPrefabComponent;
  @tracked TpkPasswordPrefab = TpkValidationPasswordPrefabComponent;
  @tracked TpkEmailPrefab = TpkValidationEmailPrefabComponent;
  @tracked TpkIbanPrefab = TpkValidationIBANPrefabComponent;
  @tracked TpkBicPrefab = TpkValidationBicPrefabComponent;
  @tracked TpkVatPrefab = TpkValidationVATPrefabComponent;
  @tracked TpkNationalNumberPrefab = TpkValidationNationalNumberPrefabComponent;
  @tracked TpkCurrencyPrefab = TpkValidationCurrencyPrefabComponent;
  @tracked TpkIntegerPrefab = TpkValidationIntegerComponent;
  @tracked TpkNumberPrefab = TpkValidationNumberPrefabComponent;
  @tracked TpkMobilePrefab = TpkValidationMobilePrefabComponent;
  @tracked TpkRadioGroup = TpkValidationRadioGroup;
  @tracked TpkRadioPrefab = TpkValidationRadioPrefabComponent;
  @tracked TpkRadioGroupPrefab = TpkValidationRadioGroupPrefabComponent;
  @tracked TpkFilePrefab = TpkValidationFilePrefabComponent;
}
