name: Tests

on: [push, release]

env:
  NODE_AUTH_TOKEN: ${{secrets.npm_token}}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Build packages before
        run: pnpm build
      - name: Run tests
        run: pnpm recursive run test
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - test
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 20
  #         registry-url: https://registry.npmjs.org/
  #         scope: "@triptyk"
  #     - uses: pnpm/action-setup@v2.2.1
  #       with:
  #         version: 8
  #         run_install: true
  #     - run: pnpm recursive publish --access=public --tag=beta
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}
