name: Tests

on: [push, release]

env:
  NODE_AUTH_TOKEN: ${{secrets.npm_token}}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - name: Build
        run: pnpm turbo build
      - name: Run tests
        run: pnpm turbo lint test
  deploy:
    runs-on: ubuntu-latest
    needs:
      - test
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          scope: "@triptyk"
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 20
      - run: pnpm recursive publish --access=public --tag=beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
